trigger:
  branches:
    include:
    - master
  tags:
    include:
      - '*'

jobs:
  - job: macOS
    pool:
      name: My-Agent

    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'
       
    - script: msbuild /p:Configuration=Release VSMacAddinSample/VSMacAddinSample/VSMacAddinSample.csproj
      displayName: 'Build VSMacAddinSample'